### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by Julusian** [bitfocus/companion-module-ventuz-director#1]
`"@types/websocket": "^1.0.4",` will need to be moved to a depenendency.
For future reference, you can check whether it will build once included by core by:
* Delete node_modules and dist
* Run `yarn --prod`
* If it didnt error, and it recreated the dist folder, then you are good

your package.json is missing some bugs and repository urls. They arent essential, but do allow us to more easily direct users to this repository eg: https://github.com/bitfocus/companion-module-behringer-xair/commit/1f4963d57f5342182bea59ac6bcbe7d54b5fcd2a

https://github.com/bitfocus/companion-module-ventuz-director/blob/0fb62417dc5931d1e7e5958e06d736302fdfaf06/src/index.ts#L107
https://github.com/bitfocus/companion-module-ventuz-director/blob/0fb62417dc5931d1e7e5958e06d736302fdfaf06/src/index.ts#L92
It would be better for you to track the feedbacks that these calls are interested in yourself (inside subscribe and unsubscribe), as `this.getAllFeedbacks()` is not a cheap call (it iterates through every feedback on every button on every page to build a list of ones for your module). In fact, you already are creating your own array of them https://github.com/bitfocus/companion-module-ventuz-director/blob/0fb62417dc5931d1e7e5958e06d736302fdfaf06/src/feedbacksProvider.ts#L23

https://github.com/bitfocus/companion-module-ventuz-director/blob/0fb62417dc5931d1e7e5958e06d736302fdfaf06/src/index.ts#L95
You should not be modifying anything on the feedback objects here, companion is currently passing a reference to the raw object that it stored internally, and writes into the db. In 2.3/3.0 this line will probably break, and that property might already be forgotten at times (when the user edits the feedback). Instead, you could store a Map of feedbackId and this value

https://github.com/bitfocus/companion-module-ventuz-director/blob/0fb62417dc5931d1e7e5958e06d736302fdfaf06/src/actionsProvider.ts#L723
Completely optional to change, but I personally would have made `this.drModuleInstance.drCompanionInfos` be a `{[id: string]: Soemthing}` or `Map<string, Something>` using `${info.page}-${info.bank}` as the id. Just to avoid doing large array iteration and risk of duplicates in the array. (there are 99x32=3168 buttons available currently and that number will increase at some point)

Again completely optional, but I would recommend considering boolean feedbacks rather than advanced feedbacks. Even though it means that there will need to be 2 feedbacks per button instead of one, it means they can be used in triggers, and in the future as parts of other 'logical expressions/checks'

**Comment by ghost** [comment]
> "@types/websocket": "^1.0.4", will need to be moved to a depenendency.

Done

> For future reference, you can check whether it will build once included by core by:

    Delete node_modules and dist
    Run yarn --prod
    If it didnt error, and it recreated the dist folder, then you are good

It runs without problems, dist folder with the according files is also created.

> your package.json is missing some bugs and repository urls. They arent essential, but do allow us to more easily direct users to this repository eg: https://github.com/bitfocus/companion-module-behringer-xair/commit/1f4963d57f5342182bea59ac6bcbe7d54b5fcd2a

Done

About the code recommendations, we have to review them, change the code and retest the module, but for the moment it seems to work stably like this (we have tested it internally).

**Comment by ghost** [comment]
Hi @Julusian I guess we can close this issue now, with the Companion V3 Upgrade all the mentioned optimizations were handled.
