### ISSUE TITLE
Ventuz Director module - WebSocket or HTTP

### ISSUE THREAD

**Issue by br1an-c0des** [bitfocus/companion-module-ventuz-director#2]
Hi!  Making a request to control Ventuz Director.  Currently using generic WebSocket to control.  Also can control via generic HTTP.

Ventuz has a fairly [comprehensive API](https://www.ventuz.com/support/help/latest/Director/DirectorRemoting.html?itm=447) for both websocket and HTTP.  Probably the most important to implement are the "Show", "Playlist", and maybe "Macro" commands.  

Would love to see a specific module that controls Ventuz Director with either protocol!  Happy to provide more feedback/suggestions if helpful. thanks very much!

**Comment by ghost** [comment]
Hi @mr-plaid 

I hope the Ventuz Director module meets your needs, the commands to control the show, playlist and macro are implemented through actions, additionally you can use feedbacks and presets as well.

Here is the complete [documentation](https://github.com/bitfocus/companion-module-ventuz-director/blob/main/HELP.md).
